version: '2'
services:
  database:
    container_name: dhis2-database
    image: pgracio/dhis2-db:2.23-training
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis
      POSTGRES_PASSWORD: dhis
      PG_DATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  web:
    container_name: dhis2-web
    image: pgracio/dhis2-web:latest
    environment:
      JAVA_OPTS: "-Xmx1024m -Xms4000m"
    ports:
      - "8085:8080"
